test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.d3d89ba1c2d8f50fe37d9f9696c01c1bada679c9.name = "Upgrade from 0.28-0~ynh4"
