#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

secret=$(ynh_string_random --length=24)
hashed_password=$(echo -n $password | sha256sum | cut -d' ' -f1)

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression "Storing installation settings..."

ynh_app_setting_set --key=secret --value=$secret
ynh_app_setting_set --key=hashed_password --value=$hashed_password

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --log="/var/log/$app.log" --log="/var/www/$app/log/production.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="lstu.conf" --destination="$install_dir/lstu.conf"

#=================================================
# INSTALL LSTU
#=================================================
ynh_script_progression "Installing Lstu..."

pushd $install_dir
	ynh_hide_warnings carton install --without=sqlite --without=mysql
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Web application available at"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
