#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

# Get is_public
password=${YNH_ACTION_PASSWORD}
hashed_password=$(echo -n $password | sha256sum | cut -d' ' -f1)

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

hashed_password_old=$(ynh_app_setting_get $app hashed_password)

if [ "$hashed_password" == "$hashed_password_old" ]
then
	ynh_die --message="Same password." --ret_code=0
fi

#=================================================
# SPECIFIC ACTION
#=================================================
# MOVE TO PUBLIC OR PRIVATE
#=================================================

ynh_backup_if_checksum_is_different "$final_path/lstu.conf"
ynh_replace_string "$hashed_password_old" "$hashed_password" "${final_path}/lstu.conf"
ynh_store_file_checksum "${final_path}/lstu.conf"

# Update the config of the app
ynh_app_setting_set $app hashed_password $hashed_password

#=================================================
# RELOAD NGINX
#=================================================

ynh_systemd_action --service_name=$app --action="reload" --log_path="systemd" --line_match="Server available at"

#=================================================
# END OF SCRIPT
#=================================================
